name: Print Secret Environment Variable

on:
  workflow_dispatch:  # Allows manual run from GitHub UI

jobs:
  print-secret:
    runs-on: ubuntu-latest

    env:
      SOME_SECRET: ${{ secrets.SOME_SECRET }}

    steps:
      - name: Print secret env variable (for test purposes only)
        run: "$SOME_SECRET"
      - run: printenv
      - run: env
